# Generated by Django 6.1 on 2026-08-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('reviewer', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('url', 'reviewer', 'date')},
            },
        ),
    ]
